Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  ExcludedMethods:
  - Gem::Specification.new
  - context
  - define
  - describe
  - it
  - let
  - let!
  - scenario
  - shared_context
  - shared_examples
  - shared_examples_for

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self
